Enhance README with examples
dblock/open-weather-ruby-client pull request #36
Opened 2024-03-14 19:57 UTC by mattlindsey

2024-03-14 20:02 UTC, dblock commented on README.md
> +client.current_city('Albany', 'NY')  # Bad: 2 letter state abbreviation without country will give Faraday::Resource not found
Say "2-letter state abbreviation w/o country will raise Faraday::ResourceNotFound" (this is the correct spelling of the error)

2024-03-14 20:02 UTC, dblock commented on README.md
> +client.current_weather(city: 'Albany', state: 'NY', country: 'US') # Good
Remove "Good"

2024-03-15 13:23 UTC, dblock requested changes
The extra " typo does need to be fixe ;) Thanks for hanging in here with me!

2024-03-15 13:23 UTC, dblock commented on README.md
> +Names that cannot be resolved will cause the API call to fail with Faraday::ResourceNotFound error.
Quote `Faraday::ResourceNotFound`

2024-03-15 13:23 UTC, dblock commented on README.md
> +client.current_city('Albany', 'NY')  # 2-letter state abbreviation w/o country will raise Faraday::ResourceNotFound"
There's an extra `"` at the end, remove.

2024-03-15 13:38 UTC, mattlindsey commented
> The extra " typo does need to be fixe ;) Thanks for hanging in here with me!
> 
> (no need for a changelog)

No problem.  Should be all set now.  :)

2024-03-15 13:58 UTC, merged