migrates to one_call 3.0
dblock/open-weather-ruby-client pull request #38
Opened 2024-06-30 13:46 UTC by jeanmartin

This doesn't take full advantage of all new One Call 3.0 features, but it adds the `summary` field to the `daily` response.

2024-07-01 00:21 UTC, dblock commented
Thanks!

Update CHANGELOG? Not sure why Danger didn't pick it up 🤔 
https://github.com/dblock/open-weather-ruby-client/blob/master/CHANGELOG.md

Increment version to 0.5.0 in this PR (version.rb, CHANGELOG, etc.), this is a major version change that breaks things.

2024-07-01 13:09 UTC, dblock requested changes
Danger is unhappy. Almost there. Thanks for hanging in here with me!

2024-07-01 13:09 UTC, dblock commented on CHANGELOG.md
> +* Your contribution here
Nit: add a period, danger complains.

2024-07-01 13:10 UTC, dblock commented on CHANGELOG.md
> +* [#38](https://github.com/dblock/open-weather-ruby-client/pull/38): Migrates to One Call 3.0 API - [@jeanmartin](https://github.com/jeanmartin).
Let's say "Migrated" to be consistent with the rest of the log.

2024-07-01 19:38 UTC, jeanmartin commented
No problem, Dangers happiness is important to me :D

2024-07-02 17:27 UTC, dblock approved these changes

2024-07-02 17:28 UTC, merged

2024-07-02 17:28 UTC, dblock commented
Thanks, merged. I'll cut a release sometime sooner than later.

2024-09-29 18:02 UTC, dblock commented
With this change I am seeing this in some logs:

```
WARN -- : Error getting weather at 50.06789, 19.92789 on 1727631664 for  ... Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info..
```

So no more free lunch?